Fix error with global let bound anonymous functions
links-lang/links pull request #1009
Opened 2021-07-10 15:29 UTC by ChefYeum

Fixes #353

2021-07-10 16:07 UTC, dhil requested changes
LGTM. Have you checked that the examples page still works?

2021-07-10 16:07 UTC, dhil commented on lib/js/jslib.js
>     * @param {any} obj
```suggestion
   * @param {any} obj
   * @return {any} obj
```

2021-07-10 16:07 UTC, dhil commented on lib/js/jslib.js
> +   * Resolve function references in the object `obj` and return the
You should note here that the resolution process fails for deeply nested structures.

2021-07-10 16:16 UTC, dhil commented on lib/js/jslib.js
> +   * Resolve function references in the object `obj` and return the
BTW you can fix this problem in a follow up PR.

2021-07-12 10:51 UTC, dhil approved these changes
LGTM.

2021-07-12 10:52 UTC, dhil commented on lib/js/jslib.js
> +   * Resolve function references in the object `obj` and return the
I have added the comment.

2021-07-12 11:11 UTC, merged

2021-07-15 13:57 UTC, SimonJF commented
FYI, `git bisect` tells me that this breaks Commands in the MVU library (see, e.g., `examples/mvu/time.links`). I get the error "`env_3442_3596.3432` is not a function".

I can look at a fix, but also happy if someone with more knowledge gets there first :)

2021-07-15 15:43 UTC, dhil commented
Hi Simon, yes this is known. @ChefYeum is working on the fix.