Introduce DateTime type
links-lang/links pull request #1028
Opened 2021-07-26 13:41 UTC by SimonJF

# Overview
The current support for dates and times in Links is a record which contains the current date and time as a record. This is difficult to compare, doesn't work well with time zones, and doesn't work with native database types.

This patch introduces a new primitive type, `DateTime`, which represents timezone-aware dates and times, and is a prerequisite for merging the temporal database work. The patch is substantial since it needs to work across all three tiers. 

# Usage

* Obtain a DateTime via...
  * the `now()` function to get a timestamp for the current local time 
  * Using `parseDate` on an ISO-formatted string (e.g., `parseDate("26-07-2021 14:26:00+1")`)
  * A `DateTime` field in the database
  * `intToDate(X)` where `X` is a UNIX timestamp
  * `beginning_of_time` and `forever`, which are special timestamps guaranteed to be less than (resp. greater than) all other timestamps

* Project fields out of the type:
  * `utcYear`, `utcMonth`, `utcDay`, `utcHours`, `utcMinutes`, `utcSeconds` projects the given field in the UTC time zone
  * `localYear`, `localMonth`, `localDay`, `localHours`, `localMinutes`, `localSeconds` projects the given field in the local time zone
  * `dateYear`, `dateMonth`, `dateDay`, `dateHours`, `dateMinutes`, `dateSeconds` projects the given field in a given timezone (e.g., to project the hours field of a `DateTime` `dt` in BST, one would write `dateHours(dt, 1)`, where `1` is the timezone offset.

Other stuff:
  * Print the `DateTime` using `show`, `showLocal`, and `showUTC`
  * Compare the `DateTime`s as normal

# Design

Timezones make things entertaining:

  * Parsing a timestamp without a timezone offset on the client or the server assumes the timestamp is in local time
  * Parsing a timestamp without a timezone offset on the database assumes the timestamp is in UTC
  * Internally the timestamp is stored as UTC, and always transferred between client and server in UTC

`DateTime` is deliberately a primitive and not an abstract type. This makes it far easier to do the database integration.

# Limitations
  * This patch doesn't support lenses yet.
  * Since only PostgreSQL supports `infinity` and `-infinity`, we only support PostgreSQL at present.
  * Because of limitations in the underlying libraries, the maximum timezone granularity is an hour. Therefore, we do not support 

# Testing / Examples
  * Server unit tests: `tests/datetime.tests`
  * Client application showcasing client functions and client<->server serialisation `examples/mvu/dates.links`
  * Database tests: `tests/shredding/dates.{sql, links}`

2021-07-26 13:43 UTC, dhil commented on core/lib.ml
> +  "beginning_of_time",
```suggestion
  "beginningOfTime",
```

2021-07-26 14:02 UTC, SimonJF commented on core/lib.ml
> +  "beginning_of_time",
Of course, how silly -- will do

2021-07-26 14:27 UTC, SimonJF commented
(Documenting):

I believe a request on the call was:

  * Change the interface for `localSeconds` and `utcSeconds` from `(DateTime) -> Float` to `(DateTime) -> Int`
  * Add `localMilliseconds` and `utcMilliseconds` with signature `(DateTime) -> Int`

This separates the implementation of the OCaml library from the library, and also gives us access to the milliseconds on the client (which as it stands are inaccessible).

There was also a request about `dateToInt`. Rest assured, this is already implemented and accessible:
```
links> dateToInt;;
dateToInt : (DateTime) ~> Int
```

2021-07-30 19:00 UTC, jamescheney commented
This obviously will have interactions with #936 (hopefully minor), which has been hanging around a while now and I'd like to get merged without unnecessary delay.

2021-07-31 17:16 UTC, SimonJF commented
Absolutely, feel free to get #936 in first; the actual DB stuff here is quite minor.

2021-08-06 16:10 UTC, dhil commented
@SimonJF is this patch ready for review?

2021-08-07 14:35 UTC, SimonJF commented
Yes, reviews would be greatly appreciated :)

2021-08-07 17:33 UTC, dhil requested changes
LGTM. My change requests are mostly concerned with code base consistency.

2021-08-07 17:33 UTC, dhil commented on core/commonTypes.ml
> +    let show x =
I suggest you add `to_string`. I can be an alias of `show` if you like.

2021-08-07 17:33 UTC, dhil commented on core/json.ml
> +        UnixTimestamp.of_calendar ts |> int_of_float in
```suggestion
        int_of_float (UnixTimestamp.of_calendar ts) in
```

2021-08-07 17:33 UTC, dhil commented on core/lib.ml
> +   datatype "(DateTime) ~> Int",
Changelog: Breaking change.

2021-08-07 17:33 UTC, dhil commented on core/lib.ml
> +  datatype "(Int) ~> DateTime",
Changelog: Breaking change.

2021-08-07 17:33 UTC, dhil commented on core/lib.ml
> +  "dateMonth", project_datetime_conv (fun dt -> CalendarShow.month dt |> CalendarLib.Date.int_of_month);
```suggestion
  "dateMonth", project_datetime_conv (CalendarShow.month ->- CalendarLib.Date.int_of_month);
```

2021-08-07 17:33 UTC, dhil commented on core/lib.ml
> +  "dateYear", (project_datetime_conv (fun dt -> CalendarShow.year dt));
```suggestion
  "dateYear", (project_datetime_conv CalendarShow.year);
```

2021-08-07 17:33 UTC, dhil commented on core/lib.ml
> +  "dateDay", project_datetime_conv (fun dt -> CalendarShow.day_of_month dt);
```suggestion
  "dateDay", project_datetime_conv CalendarShow.day_of_month;
```

2021-08-07 17:33 UTC, dhil commented on core/lib.ml
> +  "dateHours", project_datetime_conv (fun dt -> CalendarShow.hour dt);
```suggestion
  "dateHours", project_datetime_conv CalendarShow.hour;
```

2021-08-07 17:33 UTC, dhil commented on core/lib.ml
> +  "dateMinutes", project_datetime (fun dt -> CalendarShow.minute dt);
```suggestion
  "dateMinutes", project_datetime CalendarShow.minute;
```

2021-08-07 17:33 UTC, dhil commented on lib/js/jslib.js
> +const beginning_of_time = { _type: "-infinity" };
```suggestion
const beginningOfTime = { _type: "-infinity" };
```

2021-08-07 17:33 UTC, dhil commented on lib/js/jslib.js
> +    } else if (TYPES.isDate(value)) {
```suggestion
    } else if (TYPES.isDateTime(value)) {
```

2021-08-07 17:33 UTC, dhil commented on prelude.links
> +      print("Expected:\n");
```suggestion
      println("Expected:");
```

2021-08-07 17:33 UTC, dhil commented on prelude.links
>        print(show(expected));
```suggestion
      println(show(expected));
```

2021-08-07 17:33 UTC, dhil commented on prelude.links
> +      print("\nbut got:\n");
```suggestion
      println("but got:");
```

2021-08-07 17:33 UTC, dhil commented on lib/js/jslib.js
> +  isDate: function (val) {
```suggestion
  isDateTime: function (val) {
```

2021-08-12 09:20 UTC, SimonJF commented on core/lib.ml
> +  "dateMonth", project_datetime_conv (fun dt -> CalendarShow.month dt |> CalendarLib.Date.int_of_month);
Much nicer!

2021-08-12 10:38 UTC, SimonJF commented
Thanks for the reviews, @dhil. I have acted on your suggestions, and also refined the interface so we can get the milliseconds as a separate field (similar to the design of the JS Date library). I think this is good to go if you're happy, after #936 is merged.

2021-08-20 10:27 UTC, dhil approved these changes
LGTM. I will merge this now as I am about to merge in a string other PRs. I seem to recall to have promised you to merge this PR before other changes.

2021-08-20 10:40 UTC, jamescheney commented
I think this was just waiting on #936 which has not merged yet since @wricciot has been away.  The only remaining things to do on that were minor nitpicks I had, so if you can give me an hour or two I can probably just do them and that can be merged first.

2021-08-20 12:05 UTC, merged