Better workaround for issue #1187 (warning 40 due to @@deriving sexp)
links-lang/links pull request #1188
Opened 2023-10-17 14:37 UTC by frank-emrich

This PR implements a better workaround for #1187.

The previous workaround was to force using an older version of  the `ppx_sexp_conv`, which did not exhibit issue #1187. As such a version constraint may inconvenience users, this PR removes the version constraint and touches the problematic uses of `@@deriving sexp` directly.

Unforutnately, locally suppressing the warning code 40 triggered by the code generated for `@@deriving sexp` is somewhat tricky, as there is no AST node in the original source file to attach an `ocaml.warning` attribute to.

This PR circumvents this problem by wrapping the affected type definitions in an anonymous module, disabling warning 40 within that whole module, and then immediately `include`ing said module.

This limits the scope in which we actually disable warning 40 to exactly where it is needed.

2023-10-17 14:41 UTC, frank-emrich commented
I'm planning to find a better solution for #1187 eventually (e.g., looking into the generated code in detail and reporting a bug with the `ppx_sexp_conv` authors). In the meantine, this updated workaround is friendlier for end users and should be part of the upcoming Links release (as it avoids forcing users to install an outdated version of `ppx_sexp_conv`).

2023-10-18 10:15 UTC, dhil requested changes

2023-10-18 12:09 UTC, frank-emrich commented on lens/column.ml
> +  [@@@ocaml.warning "-40"]
These particular module paths are not visible from the use sites. I don't fully understand the module structure that `Sexplib` and `Sexplib0` export, but I've now `open`-ed `Sexplib0.Sexp_conv` in all the relevant (toplevel) modules instead, and gotten rid of the `include struct ... end`.

2023-11-06 11:42 UTC, dhil approved these changes
LGTM

2023-11-09 21:36 UTC, merged